import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import localFont from "next/font/local";
import "./globals.css";

// Importing custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata = {
  title: "My Ecommerce",
  description: "Generated by create next app",
};

// Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-50 text-gray-900">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Header */}
        <Navbar/>

        {/* Main Content */}
        <main className="">
          {children}
        </main>

        {/* Footer */}
        <Footer/>
      </body>
    </html>
  );
}
